### PR TITLE
First swing at basic scopes support, including some simple tests.

### PR DESCRIPTION
**Pull request by telkins**

### CODE REVIEW

**Comment by pactode** [comment]
Looks good. I’m not a fan og using `->setScope()`, when the rest of the “API” is fluid / behavioural. Perhaps, using `->scope()` would be more appropriate. Otherwise, I think it looks good. We might refactor the usage/names of traits later on, but that shouldn’t necessarily change the behaviour.

**Comment by telkins** [comment]
> Looks good. I’m not a fan og using `->setScope()`, when the rest of the “API” is fluid / behavioural. Perhaps, using `->scope()` would be more appropriate. Otherwise, I think it looks good. We might refactor the usage/names of traits later on, but that shouldn’t necessarily change the behaviour.

No worries.  I just copied/pasted/changed `HasProps` and used what was available.  I think I'll update it so that `setScope()` is protected and `scope()` is public.

And, yes, usage/name refactors can always be done....  👍

**Comment by telkins** [comment]
Actually, I took a look and figured for all the work that I might do, it might be better to wait until it's been used a bit and a clearer picture of what we want comes out.  I did change `setScope()` to `scope()`, though...

**Comment by pactode** [comment]
Thanks. I think that's a good idea. 👍

**Pull request merged**
